name: Tristan Cole
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#579bd6'
    - '#1e385e'
    - '#abc6e8'
    - '#fdc900'
    - '#b11700'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
