name: null
favicon: null
layout_spectrum: 0.6848053650464863
typography_spectrum: 0.17505007912404835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8823307976126671
  lightness: 0.17282207100652158
  saturation: 0.08966432930901647
  rhythmicContrast: 0.34745269687846303
purpose: []
