name: Tristan Cole
favicon: null
layout_spectrum: 0.56253
typography_spectrum: 0.74049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#241f20'
    - '#ddd167'
    - '#ffffff'
    - '#a6a4a4'
    - '#7f7843'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
